#+title: Màster Universitari en Professor/a d'Educació Secundària
#+bibliography: ~/Documents/Bibliography/My_Library.bib
#+cite_export: csl

* Sobre este repositori
He creat este repositori per tindre centralitzada tota la informació relativa al Màster que vaig a cursar el curs 2023-2024 i per poder realitzar un seguiment del meu treball i els coneixements que vaig adquirint.

* Format i eïnes emprades

Voldria fer notar que, si és possible, tots els programes que empraré són lliures, gratuïts i instalats localment. Evidenment, referint-me al meu entorn personal, per al treball grupal tindre que adaptar-me al que acorde el grup, així com entregar els treballs/documents en el format indicat pels professors del Màster.

** Emacs i org-mode

Tinc la idea d'emprar [[https://www.gnu.org/software/emacs/][Emacs]], [[https://orgmode.org/][org-mode]], i org-roam per processar la informació, entre altres coses, perquè al tractar-se de text pla, puc fer servir un sistema de control de versions ([[https://git-scm.com/][git]] en particular). És a dir, estes eïnes i formats constituiran la base del meu [[https://www.reddit.com/r/PKMS/][PKMS]].

*** Personalitzacions
Emacs és que es un /editor de text/ completament personalitzable mitjançant[[https://en.wikipedia.org/wiki/Emacs_Lisp][ Lisp]], així que he decidit crear algunes funcions per facilitar-me certes tarees repetitives:

- Per realitzar traduccions he instalar [[https://github.com/argosopentech/argos-translate][Argos Translate]], y he afegit funcions com la següent per poder traduir qualsevol text seleccionat:

#+BEGIN_SRC lisp
(defun translate-to-spanish ()
  "Translate selected text to spanish."
  (interactive)
  (let* ((text (buffer-substring-no-properties (region-beginning) (region-end)))
         (output (shell-command-to-string (format "echo '%s' | argos-translate --from-lang en --to-lang es" text))))
    (goto-char (region-end))
    (insert "\n" output)))
#+END_SRC

- Així mateix he afegit una petita funció per transcriure fonèticament el text seleccionat, en este cas emprant [[https://github.com/espeak-ng/espeak-ng][espeak-ng]]:

#+BEGIN_SRC lisp
  (defun transcript-selected-text-ipa ()
    "Transcript the text selected in the current buffer to ipa."
    (interactive)
    (let* ((text (buffer-substring-no-properties (region-beginning) (region-end)))
	   (escaped-text (replace-regexp-in-string "'" "'\\\\''" text))
	   (final-text (replace-regexp-in-string "\\*" "" escaped-text)))
	   (output (shell-command-to-string (format "espeak-ng '%s' -q --ipa" final-text)))
      (goto-char (region-end))
      (insert "\n" output)))
#+END_SRC

- I una funció per llegir en veu alta el text, en este cas emprant [[https://github.com/rhasspy/piper][piper]] ("Un sistema neuronal ràpid i local de text a veu que sona genial")

#+BEGIN_SRC lisp
(defun speak-selected-text ()
  "Speak the text selected."
  (interactive)
  (let* ((text (buffer-substring-no-properties (region-beginning) (region-end)))
	 (escaped-text (replace-regexp-in-string "'" "'\\\\''" text))
	 (final-text (replace-regexp-in-string "\\*" "" escaped-text)))
	 (shell-command (format "echo '%s' | piper --data-dir ~/.local/share/piper-voices/ --model ~/.local/share/piper-voices/en_GB-alba-medium.onnx  --output-raw  | aplay -r 22050 -f S16_LE -t raw" final-text))))
	 #+END_SRC

Podem notar que les 3 funcions anteriors són modificacions d'una mateixa, ja que són funcions que passen el text seleccionat a un programa extern.

** Gestió bibliogràfica
Com a gestor bibliogràfic empre [[https://www.zotero.org/][Zotero]], conjuntament amb:
 - L'[[https://www.zotero.org/download/][extensió per al navegador web]] ([[https://www.mozilla.org/en-US/firefox/][Firefox]] en el meu cas). Facilita molt baixar els documents des d'Internet, o si el que estem llegint és una pàgina web, realitzar una captura local de la mateixa. No necessite baixar-lo manualment, crear una directori o estructura de directoris, ... ja que tota la classificació la realitze directament des de Zotero.
 - El plugin [[https://retorque.re/zotero-better-bibtex/][Better Bibtex,]] que exporta la bibliografia de Zotero a format bibtex, per emprar-la en la creació de documents en els formats org-mode o $\LaTeX$, per exemple.

Emacs permet [[https://orgmode.org/manual/Citations.html][gestionar directament les cites]] dins del mode org d'una manera molt sencilla, si bé jo les gestione amb el paquet [[https://github.com/emacs-citar/citar][citar]] (el paquet [[https://github.com/jkitchin/org-ref][org-ref]] és una altra alternativa molt més completa).
Quan inserte alguna cita puc obrir el document al que fa referència (si es possible intente tindre'l com adjuntar-lo en zotero)  i, si vull, realitzar anotacions dins del propi Emacs emprant [[https://github.com/weirdNox/org-noter][org-noter]] i/o [[https://github.com/vedang/pdf-tools][pdf-tools]].


** Organització de la informació
En principi, estava decidit a guardar i classificar la documentació seguint la típica estructura de directoris, subdirectoris, ... però després d'informarme un poc sobre [[https://www.orgroam.com/][org-roam]] ([[https://www.youtube.com/watch?v=AyhPmypHDEw][este video]] considere que és una bona introducció al mateix), intentaré adoptar-lo com el sistema de gestió del coneixement [cite:@nagelKnowledgeVeryShort2014]



* Referències en aquest document  
#+print_bibliography:


