* Master de Secundaria
He creat este repositori per tindre tota la informació relativa al Màster que vaig a cursar el curs 2023-2024 centralitzada i poder realitzar un seguiment del meu treball i els coneixements que vaig adquirint.

La idea inicial és processar la informació en format org-mode, ja que al tractar-se de text pla puc fer servir un sistema de control de versions (git en particular); l'altra alternativa que m'havia plantejat és emprar el format Markdown, que si bé permet emprar moltes eïnes per processar-lo (mentre que amb el format org estic limitat quasi exclusivament a Emacs), no crec que tinga tanta versatilitat com el primer: amb el mode org d'Emacs no sols es pot editar i processar text, també mantindre llistes de tarees, agendes, ... entre moltissimes altres coses. Una altra raó important per la què m'he decitir a emprar este format és que vull aprendre a emprar Emacs i part del seu ecosistema de paquets (extensions), en particular l'esmentat org-mode, però també varis altres, alguns lligats a este, com org-roam, per gestionar, en general, tota la meua informació. És a dir, tinc la idea d'emprar Emacs, org-mode, org-roam i altres paquets com a base del meu PKMS.
