* Master de Secundaria
He creat este repositori per tindre centralitzada tota la informació relativa al Màster que vaig a cursar el curs 2023-2024 i per poder realitzar un seguiment del meu treball i els coneixements que vaig adquirint.

** Format i eïnes emprades
*** Emacs i org-mode
La idea inicial és processar la informació en el format [[https://orgmode.org/][org-mode]] d'[[https://www.gnu.org/software/emacs/][Emacs]], entre altres coses, perquè al tractar-se de text pla puc fer servir un sistema de control de versions ([[https://git-scm.com/][git]] en particular).
L'altra alternativa que m'havia plantejat és emprar el format [[https://en.wikipedia.org/wiki/Markdown][Markdown]], que si bé permet emprar moltes eïnes per processar-lo (mentre que amb el format org estic limitat exclusivament a Emacs), no crec que tinga tanta versatilitat com el primer: amb el mode org d'Emacs no sols es pot editar i processar text, també mantindre llistes de tarees, agendes, ... entre moltissimes altres coses.
Una altra raó important per la què m'he decidit a emprar este format és que vull aprendre a emprar Emacs i part del seu ecosistema de paquets (extensions), en particular l'esmentat org-mode, però també varis altres (alguns lligats a este, com org-roam), per gestionar tota la meua informació. És a dir, tinc la idea d'emprar git, Emacs, org-mode, org-roam i altres paquets com a base del meu [[https://www.reddit.com/r/PKMS/][PKMS]].

**** Configuració d'Emacs


*** Gestió bibliogràfica
Com a gestor bibliogràfic empre [[https://www.zotero.org/][Zotero]], amb l'[[https://www.zotero.org/download/][extensió]] per al navegador web ([[https://www.mozilla.org/en-US/firefox/][Firefox]] en el meu cas). Així mateix, he instalat el plugin [[https://retorque.re/zotero-better-bibtex/][Better Bibtex]] que exporta la bibliografia de Zotero a format bibtex. Emacs permet [[https://orgmode.org/manual/Citations.html][gestionar directament les cites]] dins del mode org d'una manera molt sencilla, si bé jo les gestione amb el paquet [[https://github.com/emacs-citar/citar][citar]] (el paquet [[https://github.com/jkitchin/org-ref][org-ref]] és una altra alternativa molt més completa).

*** Software lliure
Finalment voldria fer notar que, en principi, tots els programes que empraré són lliures i gratuïts.
